[package]
name = "fcv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
ratatui = { version = "*", default-features = false, features = ['termion'] }
signal-hook = "*"
anyhow = "*"
log = "*"
env_logger = "*"
clap = "*"
