= FCD-VIEW(1)
:doctype: manpage
:author: Franco Bugnano
:man source: fcd-view
:man version: 1.0.1
:man manual: fcd manual
:revdate: 2025-01-17


== NAME
fcd-view - Console file viewer


== SYNOPSIS
*fcd* _-v_ [_OPTIONS_] _FILE_

*fcd* _--view_ [_OPTIONS_] _FILE_


== DESCRIPTION
fcd-view(1) is the text based file viewer mode of fcd(1)


== OPTIONS
*-h, --help*::
	Show command line options
*-V, --version*::
	Show program's version number and exit
*-b, --nocolor*::
	Requests to run in black and white
*-v* _FILE_**, --view** _FILE_::
	File viewer
*-t* _TABSIZE_**, --tabsize** _TABSIZE_::
	Set tab size for the file viewer (default: the tab size specified in the config file)


== KEY BINDINGS
*ESC*:: Return to normal mode (like Vim)
*q, Q, v, 3, F3, 0, F10*:: Exit
*CTRL-O*:: Show console output
*j, DOWN*:: Scroll down a line
*k, UP*:: Scroll up a line
*g, HOME, CTRL-HOME*:: Go to the top of the file
*G, END, CTRL-END*:: Go to the end of the file
*CTRL-B, PAGE UP*:: Go up a page
*CTRL-F, PAGE DOWN*:: Go down a page
*w, 2, F2*:: Toggle word wrapping
*h, 4, F4*:: Toggle Hex mode
*:, 5, F5*:: Go to line number / hex offset
*/, ?, f, F, 7, F7*:: Find in file
*n*:: Find next
*N*:: Find previous


== FIND IN FILE
=== REGULAR EXPRESSION
fcd-view(1) uses the Rust dialect of regular expressions, as described in: <https://docs.rs/regex/latest/regex/index.html#syntax>

The file will be tested against the regular expression on a line-by-line basis.

=== WILDCARD SEARCH
Wildcard search uses the following wildcards:

***:: Matches everything
*?*:: Matches any single character
**[**_SEQ_**]**:: Matches any character in _SEQ_
**[!**_SEQ_**]**:: Matches any character not in _SEQ_

The file will be tested against the wildcard expression on a line-by-line basis.

==== EXAMPLE
sp* eg?s:: Search for "sp" followed by any number of characters, space, "eg", followed by one character, and "s".

=== HEXADECIMAL
When in hex mode, the search function accepts text in quotes and constant
numbers. Text in quotes is matched exactly after removing the quotes. Each
number matches one or more bytes. You can mix quoted text with constants like this:

"String" 34 0xBB 012 "more text"

Numbers are always interpreted in hex. In the example above, "34" is
interpreted as 0x34. The prefix "0x" isn't really needed: we could type "BB"
instead of "0xBB". And "012" is interpreted as 0x00 0x12, not as an octal number.


== RESOURCES
GitHub: <https://github.com/bugnano/fcd>

Crates: <https://crates.io/crates/fcd/>


== SEE ALSO
fcd(1)


== COPYING
Copyright \(C) 2023-2025 Franco Bugnano. Free use of this software is
granted under the terms of the GNU General Public License (GPL).

