[ui]
hotkey_fg = "white"
hotkey_bg = "black"
selected_fg = "black"
#selected_bg = { user = "cyan", root = "red" }
selected_bg = "cyan"

use_shadows = true
shadow_fg = "darkgray"
shadow_bg = "black"

[error]
fg = "white"
bg = "red"
title_fg = "lightyellow"
focus_fg = "black"
focus_bg = "gray"

[dialog]
fg = "black"
bg = "gray"
title_fg = "blue"
focus_fg = "black"
focus_bg = "cyan"

placeholder_fg = "darkgray"
input_fg = "black"
input_bg = "cyan"

[viewer]
tab_size = 4

[highlight]
# Default Background
base00 = "blue"

# Comments, Invisibles, Line Highlighting
base03 = "cyan"

# Default Foreground, Caret, Delimiters, Operators
base05 = "gray"

# Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base08 = "lightyellow"

# Integers, Boolean, Constants, XML Attributes, Markup Link Url
base09 = "lightmagenta"

# Classes, Markup Bold, Search Text Background
base0A = "lightred"

# Strings, Inherited Class, Markup Code, Diff Inserted
base0B = "lightcyan"

# Support, Regular Expressions, Escape Characters, Markup Quotes
base0C = "white"

# Functions, Methods, Attribute IDs, Headings
base0D = "lightred"

# Keywords, Storage, Selector, Markup Italic, Diff Changed
base0E = "lightyellow"

# Deprecated, Opening/Closing Embedded Language Tags, e.g. `<?php ?>`
base0F = "lightyellow"

