[ui]
hotkey_fg = "white"
hotkey_bg = "black"
selected_fg = "black"
#selected_bg = { user = "cyan", root = "red" }
selected_bg = "cyan"

marked_fg = "light yellow"
markselect_fg = "light yellow"

use_shadows = true
shadow_fg = "dark gray"
shadow_bg = "black"

error_fg = "light red"
error_bg = "reset"

[panel]
fg = "gray"
bg = "blue"
reverse_fg = "black"
reverse_bg = "gray"

[error]
fg = "white"
bg = "red"
title_fg = "light yellow"
focus_fg = "black"
focus_bg = "gray"

[dialog]
fg = "black"
bg = "gray"
title_fg = "blue"
focus_fg = "black"
focus_bg = "cyan"

placeholder_fg = "dark gray"
input_fg = "black"
input_bg = "cyan"

[file_manager]
directory_fg = "white"
dir_symlink_fg = "white"
executable_fg = "light green"
symlink_fg = "gray"
stalelink_fg = "light red"
device_fg = "light magenta"
special_fg = "black"
archive_fg = "light magenta"

[viewer]
tab_size = 4

lineno_fg = "white"
hex_even_fg = "cyan"
hex_odd_fg = "gray"
hex_text_even_fg = "cyan"
hex_text_odd_fg = "gray"

[highlight]
# Default Background
base00 = "blue"

# Comments, Invisibles, Line Highlighting
base03 = "cyan"

# Default Foreground, Caret, Delimiters, Operators
base05 = "gray"

# Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base08 = "light yellow"

# Integers, Boolean, Constants, XML Attributes, Markup Link Url
base09 = "light magenta"

# Classes, Markup Bold, Search Text Background
base0A = "light red"

# Strings, Inherited Class, Markup Code, Diff Inserted
base0B = "light cyan"

# Support, Regular Expressions, Escape Characters, Markup Quotes
base0C = "white"

# Functions, Methods, Attribute IDs, Headings
base0D = "light red"

# Keywords, Storage, Selector, Markup Italic, Diff Changed
base0E = "light yellow"

# Deprecated, Opening/Closing Embedded Language Tags, e.g. `<?php ?>`
base0F = "light yellow"

