name: Build

on: workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # platform: [linux/amd64, linux/arm64]
        platform: [linux/amd64]
        include:
          - platform: linux/amd64
            target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
          # - platform: linux/arm64
          #   target: aarch64-unknown-linux-musl
          #   runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Linux
        run: |
          docker run --platform ${{ matrix.platform }} --rm -t \
            -v $HOME/.cargo/registry/:/root/.cargo/registry \
            -v "$(pwd)":/volume \
            clux/muslrust:stable \
            env CFLAGS=-Os cargo build --release --target ${{ matrix.target }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fcd-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/fcd
          if-no-files-found: error
